# Generated by Django 5.0.7 on 2024-07-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='todo', max_length=20)),
                ('creating_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
